// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace these with your actual Firebase project configuration

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ-zI4UrZxL2Z6qvt4qfEsDPnmgrm5iuI',
    appId: '1:13557902076:web:44d0c76a6fad7aca514579',
    messagingSenderId: '13557902076',
    projectId: 'roll-and-read',
    authDomain: 'roll-and-read.firebaseapp.com',
    storageBucket: 'roll-and-read.firebasestorage.app',
  );

  // You can find these in your Firebase Console > Project Settings > General

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQSjGc2I1bURyF0LrUIJuVJRM2L3ClwhE',
    appId: '1:13557902076:android:060c2b521a99aa2b514579',
    messagingSenderId: '13557902076',
    projectId: 'roll-and-read',
    storageBucket: 'roll-and-read.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgV_pzWg0rqc9YiGQwmNZvwyjA4NBR_f8',
    appId: '1:13557902076:ios:2aff37883ba1fb45514579',
    messagingSenderId: '13557902076',
    projectId: 'roll-and-read',
    storageBucket: 'roll-and-read.firebasestorage.app',
    iosBundleId: 'com.llc.rollAndRead',
  );

}